#!/bin/bash
# 4. add dtbs to extlinux.conf
# Define source and destination directories
DTB_SOURCE_DIR="/boot/dtb/uthp/"
EXTLINUX_DIR="/boot/p1/extlinux/"
EXTLINUX_CONF="/boot/p1/extlinux/extlinux.conf"

# Check if source and destination directories exist
if [ ! -d "$DTB_SOURCE_DIR" ]; then
    echo "Source directory $DTB_SOURCE_DIR does not exist."
    exit 1
fi

if [ ! -d "$EXTLINUX_DIR" ]; then
    echo "Destination directory $EXTLINUX_DIR does not exist."
    mkdir -p "$EXTLINUX_DIR"
fi

# Copy some specific .dtbo files to source directory
# (these are added by ti)
cp /boot/dtb/BB-I2C1-MCP7940X-00A0.dtbo "$DTB_SOURCE_DIR"
cp /boot/dtb/BB-UART4-00A0.dtbo "$DTB_SOURCE_DIR"
cp /boot/dtb/BB-UART2-00A0.dtbo "$DTB_SOURCE_DIR"

# Copy all *.dtbo files from source to destination directory
# (these are added by us)
cp "$DTB_SOURCE_DIR"*.dtbo "$EXTLINUX_DIR"

# Backup the extlinux.conf file
cp "$EXTLINUX_CONF" "${EXTLINUX_CONF}.backup.$(date +%Y%m%d%H%M%S)"

# Prepare the FDTOVERLAYS line
FDTOVERLAYS="FDTOVERLAYS"
for dtbo_file in "$EXTLINUX_DIR"*.dtbo; do
    dtbo_filename=$(basename "$dtbo_file")
    FDTOVERLAYS="${FDTOVERLAYS} ./${dtbo_filename}"
done

# Insert the FDTOVERLAYS line after the FDTDIR line and before the APPEND line
# First, remove any existing FDTOVERLAYS line
sed -i '/FDTOVERLAYS/d' "$EXTLINUX_CONF"

# Insert the new FDTOVERLAYS line
sed -i "/FDTDIR ../a \\\t${FDTOVERLAYS}" "$EXTLINUX_CONF"

echo "The .dtbo files have been added to the extlinux.conf file as a single FDTOVERLAYS line as follows:"
cat "$EXTLINUX_CONF" | grep FDTOVERLAYS

echo "==> Added .dtbo files to extlinux.conf"

### UPDATES ###
# every 10 mins this script can be run from a service file
# or
# can be run from /usr/bin/update-overlays
# can check with show-pins utility
# maybe use softlinks ???